Add contribution guide
rust-practice/cargo-leet pull request #55
Opened 2023-07-27 18:38 UTC by nassersaazi

Fixes #52

2023-07-29 22:14 UTC, c-git commented on CONTRIBUTING.md
> +The best place to start is to check the [issues](https://github.com/rust-practice/cargo-leet)
I was wondering if we should also point them at the discussion in case they find something in there more interesting.

2023-07-29 22:16 UTC, c-git commented on CONTRIBUTING.md
> +* Explain what is currently happening and what you expect instead.
For this one maybe we should point them at the templates? https://github.com/rust-practice/cargo-leet/issues/new/choose

2023-07-29 22:19 UTC, c-git commented on CONTRIBUTING.md
> +git clone git@github.com:your-user-name/cargo-leet
Doesn't it need the `.git` at the end?

```suggestion
git clone git@github.com:your-user-name/cargo-leet.git
```

2023-07-29 22:21 UTC, c-git commented on CONTRIBUTING.md
> +cargo test
For this one maybe we should recommend `cargo t` instead as we've aliased that one to test all features

```suggestion
cargo t
```

2023-07-29 22:22 UTC, c-git commented on CONTRIBUTING.md
> +
Maybe we should remove `chargo check` as both `cargo clippy` and `cargo t` will do this

2023-07-29 22:23 UTC, c-git commented on CONTRIBUTING.md
> +Once your changes are ready and all linting/tests are passing you can push your changes to your forked repositry:
I think you might have a typo

```suggestion
Once your changes are ready and all linting/tests are passing you can push your changes to your forked repository:
```

2023-07-29 22:24 UTC, c-git commented on CONTRIBUTING.md
> +origin is the default name of your remote repositry on GitHub. You can see all of your remote repositories by running:
Same typo here

```suggestion
origin is the default name of your remote repository on GitHub. You can see all of your remote repositories by running:
```

2023-07-29 22:26 UTC, c-git commented on CONTRIBUTING.md
> +1. Select the base and compare branches, if necessary. This will be main and my-new-feature, respectively.
I think it might be better for them to make pull requests against develop (which will be the default based on how we have the repo setup)

2023-07-29 22:27 UTC, c-git commented on CONTRIBUTING.md
> +There may be some merge conficts that need to be resolved. After the feature branch has been update
Typo

```suggestion
There may be some merge conflicts that need to be resolved. After the feature branch has been update
```

2023-07-29 22:29 UTC, c-git requested changes
Mostly looks good, I added a few comments for your review / feedback / action.

2024-01-12 19:36 UTC, c-git approved these changes
I think it looks ok now.

2024-01-22 00:16 UTC, AliciaY-720 approved these changes
looks good

2024-01-22 02:02 UTC, c-git commented
Thanks

2024-01-22 02:02 UTC, merged